# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170414_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='streamfield',
        ),
    ]
