# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_standardpage_streamfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='contact_email',
            field=models.EmailField(help_text='Email address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='contact_telephone',
            field=models.CharField(help_text='Telephone', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='contact_twitter',
            field=models.CharField(help_text='Twitter', max_length=255, null=True),
        ),
    ]
