# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-16 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('core', '0007_auto_20170414_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='work_title',
            new_name='article_title',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
