# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170416_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupformpage',
            name='formatted_title',
            field=models.CharField(blank=True, help_text='This is the title displayed on the page, not the document title tag. HTML is permitted (Remember Ibraheem).', max_length=255),
        ),
        migrations.AlterField(
            model_name='signupformpagebullet',
            name='icon',
            field=models.CharField(choices=[('core/includes/svg/bulb-svg.html', 'Light bulb'), ('core/includes/svg/pro-svg.html', 'Chart'), ('core/includes/svg/tick-svg.html', 'Tick')], max_length=100),
        ),
    ]
