# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170418_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_intro_primary',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_intro_secondary',
        ),
    ]
