# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170418_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='main_image',
        ),
    ]
