# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('core', '0011_remove_articlepage_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='marketing_only',
            field=models.BooleanField(default=False, help_text='Display this article post only on marketing landing page'),
        ),
    ]
